name: my_first_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit: 4.9.1
  share_plus: ^12.0.1
  stacked: ^3.5.0
  stacked_services: "^1.6.0"
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0
  golden_toolkit: ^0.15.0
  retrofit_generator: ^10.2.0

flutter:
  uses-material-design: true


  assets:
    - lib/core/translations/